add picom compositor for transparent nofi window

diff --git a/bin/nofi b/bin/nofi
--- a/bin/nofi
+++ b/bin/nofi
@@ -4,11 +4,23 @@
 
 # ---- Start unofficial bash strict mode boilerplate
 # http://redsymbol.net/articles/unofficial-bash-strict-mode/
-set -o errexit # always exit on error
+set -o errexit  # always exit on error
 set -o errtrace # trap errors in functions as well
 set -o pipefail # don't ignore exit codes when piping output
 # set -x # enable debugging
 
 IFS=$'\n\t'
 # ---- End unofficial bash strict mode boilerplate
-kitty --class nofi --start-as normal --config ~/.config/kitty/kitty.conf --config ~/.config/kitty/nofi.conf --session ~/.config/kitty/nofi.session
+declare -a opts=(
+  --class nofi
+  --start-as normal
+  --config ~/.config/kitty/kitty.conf
+  --config ~/.config/kitty/nofi.conf
+  --session ~/.config/kitty/nofi.session
+)
+
+if pgrep --exact picom >/dev/null; then
+  opts=("${opts[@]}" --override 'background_opacity=0.4')
+fi
+
+kitty "${opts[@]}"
