Fixed major bug in prompt-or-clipboard

diff --git a/bin/prompt-or-clipboard b/bin/prompt-or-clipboard
--- a/bin/prompt-or-clipboard
+++ b/bin/prompt-or-clipboard
@@ -1,16 +1,26 @@
-#!/usr/bin/env zsh
+#!/usr/bin/env bash
+
+# Please Use Google Shell Style: https://google.github.io/styleguide/shell.xml
+
+# ---- Start unofficial bash strict mode boilerplate
+# http://redsymbol.net/articles/unofficial-bash-strict-mode/
 set -o errexit  # always exit on error
+set -o errtrace # trap errors in functions as well
 set -o pipefail # don't ignore exit codes when piping output
+set -o posix    # more strict failures in subshells
 # set -x          # enable debugging
 
-IFS='$\n\t'
+IFS=$'\n\t'
+# ---- End unofficial bash strict mode boilerplate
+
 query=
 label="${1:-query}"
 clipboard_preview=$(~/bin/paste | head -c 12 | tr '\n' ' ')
 clipboard_hint="ENTER for 📋 (${clipboard_preview}…)"
+#if false; then
 if [[ -t 1 ]]; then
   echo "${clipboard_hint}" >/dev/tty
-  vared -p "${label}: " query
+  query=$(zsh -c "query=; vared -p \"${label}: \" query; echo \"\${query}\"")
 else
   query=$(zenity --entry --title="${label}" --text="${clipboard_hint}\n\n${label}" --width=500)
 fi
